[Interface]
Address = 10.13.13.3
PrivateKey = uK0uQAT58zyH+OyJZiv8LYUOUv22xSAhEHKVL6WAOk0=
ListenPort = 51820
DNS = 10.13.13.1

[Peer]
PublicKey = +PgMmmgpgVbTQd2Ky1xHO15luenP60yfs5L7jwbmv0I=
PresharedKey = g3DAiGvgPyCR9JkKhu0XKp/3t2rcxC5qxOrMCDuX6wk=
Endpoint = 86.127.228.132:51820
AllowedIPs = 0.0.0.0/0, ::/0
