[Interface]
Address = 10.13.13.4
PrivateKey = 0BTSN0VwrDvnPofxTG+Nl6DpaElvvl6Bgun9NPumIH4=
ListenPort = 51820
DNS = 10.13.13.1

[Peer]
PublicKey = +PgMmmgpgVbTQd2Ky1xHO15luenP60yfs5L7jwbmv0I=
PresharedKey = vAoVauubZ3kya7dO5HJuJLOlrpXyzRn0gKumZpdrqbs=
Endpoint = 86.127.228.132:51820
AllowedIPs = 0.0.0.0/0, ::/0
